set guifont=Iosevka\ Fusion\ 13
set guioptions-=T
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=e

nnoremap <Leader>egv <Cmd>edit   $MYGVIMRC<CR>
nnoremap <Leader>sgv <Cmd>source $MYGVIMRC<CR>

nnoremap <C-F1> <Cmd>silent! call <SID>toggle_gui_option('m')<CR>
nnoremap <C-F2> <Cmd>silent! call <SID>toggle_gui_option('T')<CR>
nnoremap <C-F3> <Cmd>silent! call <SID>toggle_gui_option('r')<CR>

function! s:toggle_gui_option(option) abort
    if &guioptions =~# a:option
        let &guioptions = substitute(&guioptions, a:option, '', 'g')
    else
        let &guioptions ..= a:option
    endif
endfunction
