if has('macunix') | set guifont=SF_Mono:h16 | endif
if has('win64')   | set guifont=SF_Mono:h12 | endif

set guioptions-=T
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=e

if has('macunix') | set guioptions+=e              | endif
if has('win64')   | set renderoptions=type:directx | endif

nnoremap <Leader>egv <Cmd>edit   $MYGVIMRC<CR>
nnoremap <Leader>sgv <Cmd>source $MYGVIMRC<CR>

tnoremap <Esc> <C-\><C-N>

nnoremap <C-F1> <Cmd>silent! call <SID>toggle_gui_option('m')<CR>
nnoremap <C-F2> <Cmd>silent! call <SID>toggle_gui_option('T')<CR>
nnoremap <C-F3> <Cmd>silent! call <SID>toggle_gui_option('r')<CR>

function! s:toggle_gui_option(option) abort
    if &guioptions =~# a:option
        let &guioptions = substitute(&guioptions, a:option, '', 'g')
    else
        let &guioptions ..= a:option
    endif
endfunction
