set ch=2		" Make command line two lines high
set mousehide		" Hide the mouse when typing text
set guioptions-=T guioptions-=m guioptions-=L guioptions-=r guioptions-=e
set guifont=Iosevka\ Fusion\ 13

colorscheme zellner

nnoremap <Leader>egv :edit $MYGVIMRC<CR>
nnoremap <Leader>sgv :source $MYGVIMRC<CR>

nnoremap <C-F1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<CR>
nnoremap <C-F2> :if &go=~#'t'<Bar>set go-=t<Bar>else<Bar>set go+=t<Bar>endif<CR>
nnoremap <C-F3> :if &go=~#'r'<Bar>set go-=r<Bar>else<Bar>set go+=r<Bar>endif<CR>

" Make shift-insert work like in Xterm
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

