set nocompatible encoding=utf-8 fileencoding=utf-8 nrformats-=octal
filetype plugin indent on 

set number relativenumber cursorline showcmd wildmenu lazyredraw showmatch ruler hidden
set autoindent smartindent smarttab expandtab tabstop=2 shiftwidth=2 softtabstop=2
set smartcase incsearch hlsearch ignorecase shortmess+=I
set mouse=a

if has('win32') "Windows
  set viminfo=%,<800,'10,/50,:100,h,f0,n~/vimfiles/cache/.viminfo
else
  set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/.viminfo
endif

syntax enable
" set termguicolors
" set background=light

let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']

" key mappings
nnoremap Y y$
nnoremap <leader>cd :cd %:p:h<cr>:pwd<cr>
nnoremap <leader>ev :e $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
nnoremap <leader>egv :e $MYGVIMRC<cr>
nnoremap <leader>sgv :source $MYGVIMRC<cr>

" minpac 
if exists('*minpac#init')
  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  call minpac#add('jiangmiao/auto-pairs', {'name': 'vim-auto-pairs'})
  call minpac#add('tpope/vim-commentary')
  call minpac#add('tpope/vim-fugitive')
  call minpac#add('machakann/vim-highlightedyank', {'name': 'vim-highlighted-yank'})
  call minpac#add('unblevable/quick-scope', {'name': 'vim-quick-scope'})
  call minpac#add('tpope/vim-repeat')
  call minpac#add('tpope/vim-surround')
  call minpac#add('tpope/vim-unimpaired')
endif

" Define user commands for updating/cleaning the plugins.
" Each of them loads minpac, reloads .vimrc to register the
" information of plugins, then performs the task.
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update('', {'do': 'call minpac#status()'})
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
command! PackStatus packadd minpac | source $MYVIMRC | call minpac#status()
