[buildPlans.iosevka-fusion]
family     = "Iosevka Fusion"
spacing    = "fixed"
serifs     = "sans"
digit-form = "lining"

[buildPlans.iosevka-fusion.variants]
inherits = "ss08"

[buildPlans.iosevka-fusion.variants.design]
i         = 'hooky'
l         = 'italic'
zero      = 'long-dotted'
brace     = 'curly'
ampersand = 'closed'
dollar    = 'through'
percent   = 'rings'

[buildPlans.iosevka-fusion.variants.upright]
f = 'flat-hook-crossbar-at-x-height'
j = 'flat-hook-serifed'
t = 'flat-hook'

[buildPlans.iosevka-fusion.variants.italic]
f = 'flat-hook-round-tailed-crossbar-at-x-height'
j = 'serifed'
t = 'standard'

[buildPlans.iosevka-fusion.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-fusion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-fusion.weights.book]
shape = 450
menu  = 450
css   = 450

[buildPlans.iosevka-fusion.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-fusion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-fusion.slopes]
upright = "normal"
italic  = "italic"

[buildPlans.iosevka-fusion.widths.normal]
shape = 576
menu  = 5
css   = "normal"
