[buildPlans.iosevka-fusion]
family = "Iosevka Fusion"
design = [
          "ss08",
          "sp-fixed",
          "v-f-flat-hook-crossbar-at-x-height",
          "v-l-italic",
          "v-zero-long-dotted",
          "v-brace-curly",
          "v-ampersand-closed",
          "v-dollar-through",
          "v-percent-rings",
          "no-cv-ss"
         ]
italic = ["v-f-flat-hook-round-tailed-crossbar-at-x-height"]
hintParams = ["-a", "sss"]

[buildPlans.iosevka-fusion.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-fusion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-fusion.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-fusion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-fusion.slopes]
upright = "normal"
italic  = "italic"

[buildPlans.iosevka-fusion.widths.normal]
shape = 576
menu  = 5
css   = "normal"
