[buildPlans.iosevka-fusion]
family = "Iosevka Fusion"
design = [ "ss20"
         , "sp-fixed"
         , "no-cv-ss"
         , "v-g-doublestorey"
         , "v-zero-dotted"
         , "v-six-closed-contour"
         , "v-nine-closed-contour"
         , "v-numbersign-slanted"
         ]

[buildPlans.iosevka-fusion.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-fusion.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-fusion.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-fusion.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-fusion.slopes]
upright = "normal"
italic  = "italic"

[buildPlans.iosevka-fusion.widths.normal]
shape = 576
menu  = 5
css   = "normal"
