#!/usr/bin/env bash

export BSPWM_HOME=$HOME/.config/bspwm
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 0

bspc config border_width          1
bspc config window_gap            1
bspc config split_ratio           0.52
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           35

bspc config active_border_color   "#8f0075" #color4
bspc config focused_border_color  "#3548cf" #color5
bspc config normal_border_color   "#ffffff" #background
bspc config presel_feedback_color "#bbc3ff" #color8

bspc rule -a termbar manage=off focus=off
bspc rule -a Emacs state=tiled
bspc rule -a fzmenu state=floating focus=on center=on rectangle=400x400+0+0

# firefox
bspc rule -a firefox:Browser focus=on state=floating center=on

# start ibus daemon
ibus-daemon --daemonize --replace --xim &

# terminate already running bar instances
pkill -u $UID -f termbar

# wait until the processes have been shut down
while pgrep -u $UID -f termbar >/dev/null; do sleep 1; done

exec -a termbar kitty                                             \
     --class termbar                                              \
     --config $BSPWM_HOME/termbar.kitty.conf                       \
     --override open_url_with=$BSPWM_HOME/termbar-protocol-handler \
     --single-instance                                            \
     --instance-group=termbar                                     \
     -- $BSPWM_HOME/termbar 0 &
