#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 0

bspc config border_width          1
bspc config window_gap            1
bspc config split_ratio           0.52
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color   "#ffffff" #background
bspc config active_border_color   "#3464a4" #color4
bspc config focused_border_color  "#74507a" #color5
bspc config presel_feedback_color "#545753" #color8

bspc rule -a XTerm            desktop='^1'
bspc rule -a Firefox          desktop='^2'
bspc rule -a Google-chrome    desktop='^2'
bspc rule -a Chromium-browser desktop='^2'
bspc rule -a Thunderbird      desktop='^3'
bspc rule -a Nvim             desktop='^4' state=tiled
bspc rule -a Gvim             desktop='^4' state=tiled
bspc rule -a Emacs            desktop='^4' state=tiled
bspc rule -a Code             desktop='^5' 
bspc rule -a jetbrains-clion  desktop='^5' 
bspc rule -a Soffice          desktop='^6'
bspc rule -a libreoffice      desktop='^6'
bspc rule -a Zathura          desktop='^6' state=tiled
bspc rule -a mpv              desktop='^7' 
bspc rule -a dosbox           desktop='^7' 
bspc rule -a pyrogenesis      desktop='^7' 
bspc rule -a Virt-manager     desktop='^8' 
bspc rule -a Yad              border=on    state=floating

# initialize the session
~/.config/bspwm/scripts/init_session &
