#! /bin/sh

sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 
bspc monitor HDMI-1 -d 9 0

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         0
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bspc rule -a XTerm desktop='^1'
bspc rule -a kitty desktop='^1'

bspc rule -a firefox desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a Opera desktop='^2'

bspc rule -a nvim desktop='^3' state=tiled
bspc rule -a vim desktop='^3' state=tiled
bspc rule -a Gvim desktop='^3' state=tiled
bspc rule -a Emacs desktop='^3' state=tiled

bspc rule -a jetbrains-clion desktop='^4' 
# bspc rule -a jetbrains-idea desktop='^4' 
# bspc rule -a jetbrains-webstorm desktop='^4' 

# documents
bspc rule -a Soffice desktop='^5'
bspc rule -a libreoffice desktop='^5'
# bspc rule -a Wps desktop='^5'
# bspc rule -a Et desktop='^5'
# bspc rule -a Wpp desktop='^5'
# bspc rule -a Wpspdf desktop='^5'
bspc rule -a Zathura desktop='^5' state=tiled

# entertainment
bspc rule -a mpv desktop='^6' 

# game
bspc rule -a pyrogenesis desktop='^7' 
bspc rule -a dosbox desktop='^7' 

# misc.
bspc rule -a Yad state=floating

# initialize the session
~/.config/scripts/bspwm_init_session &
