#!/usr/bin/env bash

if [[ $1 =~ ^tbp:\/\/wm\/ws\/[1-9]$ ]]; then # tbp://wm/ws/${tag_name}
    tag=${1##*/}
    bspc desktop --focus "${tag}"
elif [[ $1 =~ ^tbp:\/\/wm\/bye$ ]]; then # tbp://wm/bye
    kitty --class fzmenu $BSPWM_HOME/sayonara
fi
