#!/bin/sh

# chosen=$(echo -e "[Cancel]\nLock\nLogout\nReboot\nShutdown\nSuspend\nHibernate" | rofi -dmenu -i -p "Leaving bspwm ... ")
# chosen=$(echo -e "\tLock\n\tLogout\n\tReboot\n\tShutdown" | rofi -dmenu -i -p "Leaving bspwm ... ")
chosen=$(echo -e "\tLock\n\tLogout\n‎ﰇ\tReboot\n\tShutdown" | rofi -dmenu -i -p "Leaving bspwm ... ")

if [[ $chosen =~ "Lock" ]]; then
    light-locker-command --lock
elif [[ $chosen =~ "Logout" ]]; then
    bspc quit
elif [[ $chosen =~ "Reboot" ]]; then
    systemctl reboot
elif [[ $chosen =~ "Shutdown" ]]; then
    systemctl poweroff
fi


# yad --center --width=500 \
#   --image=fedora-logo-icon \
#   --text "<b>Are you sure to leave bspwm?</b>" \
#   --button=gtk-cancel:0 --button=" Lock!system-lock-screen-symbolic":1 --button=" Logout!system-log-out-symbolic":2 --button=" Reboot!system-reboot-symbolic":3 --button=" Shutdown!system-shutdown-symbolic":4

# case "$?" in
#   1)  light-locker-command --lock
#     ;;
#   2)  bspc quit
#     ;;
#   3)  systemctl reboot
#     ;;
#   4)  systemctl poweroff
#     ;;
#   *) ;;
# esac


# yad --form --text "are you sure?" \
#   --field=gtk-cancel:fbtn 0 \
#   --field="lock":fbtn 1 \
#   --field="logout":fbtn 2 \
#   --no-buttons

# echo $?
  
