#!/bin/sh

xrdb ~/.Xresources

# autostart some programs
picom --daemon --fading --no-fading-openclose 
xsetroot -cursor_name left_ptr 
xset s 300 5 
xset m 3/2 3
light-locker &

[[ -x $HOME/.fehbg ]] && $HOME/.fehbg

# workaround a java bug for jetbrain products
wmname LG3D 

# lightdm doesn't source .xprofile
# source ~/.xprofile

# launch polybar
~/.config/bspwm/scripts/launch_polybar 
