#!/bin/sh

chosen=$(echo -e "\tLock\n\tLogout\n‎ﰇ\tReboot\n\tShutdown" | rofi -dmenu -i -p "Leaving bspwm ... ")

if [[ $chosen =~ "Lock" ]]; then
    light-locker-command --lock
elif [[ $chosen =~ "Logout" ]]; then
    herbstclient quit
elif [[ $chosen =~ "Reboot" ]]; then
    systemctl reboot
elif [[ $chosen =~ "Shutdown" ]]; then
    systemctl poweroff
fi
