#!/usr/bin/bash

hc() {
    herbstclient "$@"
}

xrdb ~/.Xresources

# launch a few programs
xsetroot -cursor_name left_ptr 
xset s 300 5 
picom --daemon --fading --no-fading-openclose
light-locker &

if [ -f $HOME/.fehbg ]; then
  hc spawn $HOME/.fehbg
fi

# lightdm doesn't source .xprofile
source ~/.xprofile

# launch polybar
polybar=~/.config/herbstluftwm/scripts/launch_polybar
if [ -x "$polybar" ]; then
  # padding to accomodate polybar
  hc pad 0 32 0 0 0

  # launch 
  $polybar
fi
