#!/usr/bin/env bash

# https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/info-hlwm-workspaces

icons=(
        󱆃   #1
        󰖟   #2
        󰇰   #3
        󰷉   #4
        󰊢   #5
        󱉟   #6
        󰛊   #7
        󰢹   #8
        󰚀   #9
      )

herbstclient --idle "tag_*" 2>/dev/null | {

    while true; do
        # Read tags into $tags as array
        IFS=$'\t' read -ra tags <<< "$(herbstclient tag_status)"
        {
            for i in "${tags[@]}" ; do
                # Read the prefix from each tag and render them according to that prefix
                case ${i:0:1} in
                    '#')
                        # the tag is viewed on the focused monitor
                        # TODO Add your formatting tags for focused workspaces
                        echo "%{F#cc0000}"
                        ;;
                    ':')
                        # : the tag is not empty
                        # TODO Add your formatting tags for occupied workspaces
                        echo "%{F#545753}"
                        ;;
                    '!')
                        # ! the tag contains an urgent window
                        # TODO Add your formatting tags for workspaces with the urgent hint
                        ;;
                    '-')
                        # - the tag is viewed on a monitor that is not focused
                        # TODO Add your formatting tags for visible but not focused workspaces
                        ;;
                    *)
                        # . the tag is empty
                        # There are also other possible prefixes but they won't appear here
                        # echo "%{F-}%{B-}" # Add your formatting tags for empty workspaces
                        echo "%{F#ededec}"
                        ;;
                esac

                echo "%{A1:herbstclient use ${i:1}:} ${icons[((${i:1}-1))]} %{A -u -o F- B-}"
            done

            echo "%{F-}%{B-}"
        } | tr -d "\n"

    echo

    # wait for next event from herbstclient --idle
    read -r || break
done
} 2>/dev/null
