#!/usr/bin/env bash

width=200
height=100
posx=-1
posy=32

PATH_AC="/sys/class/power_supply/AC"
PATH_BATTERY_0="/sys/class/power_supply/BAT0"
PATH_BATTERY_1="/sys/class/power_supply/BAT1"

ac=0
battery_level_0=0
battery_level_1=0
battery_max_0=0
battery_max_1=0

[ -f "$PATH_AC/online" ]             && ac=$(cat "$PATH_AC/online")
[ -f "$PATH_BATTERY_0/energy_now" ]  && battery_level_0=$(cat "$PATH_BATTERY_0/energy_now")
[ -f "$PATH_BATTERY_1/energy_now" ]  && battery_level_1=$(cat "$PATH_BATTERY_1/energy_now")
[ -f "$PATH_BATTERY_0/energy_full" ] && battery_max_0=$(cat "$PATH_BATTERY_0/energy_full")
[ -f "$PATH_BATTERY_1/energy_full" ] && battery_max_1=$(cat "$PATH_BATTERY_1/energy_full")

battery_percent_0=$(("$battery_level_0 * 100 / $battery_max_0"))
battery_percent_1=$(("$battery_level_1 * 100 / $battery_max_1"))

battery_level=$(("$battery_level_0 + $battery_level_1"))
battery_max=$(("$battery_max_0 + $battery_max_1"))

battery_percent=$(("$battery_level * 100"))
battery_percent=$(("$battery_percent / $battery_max"))

# # calculate the percentage in 10s
# battery_percent_level=$(("battery_percent / 10 * 10"))
# if [ "$ac" -eq 1 ]; then
#   image="battery-level-$battery_percent_level-charging-symbolic"
#   [ "$battery_percent" -eq 100 ] && image="battery-level-$battery_percent_level-charged-symbolic"
# else
#   image="battery-level-$battery_percent_level-symbolic"
# fi

yad --width=$width \
  --height=$height \
  --posx=$posx \
  --posy=$posy \
  --no-buttons \
  --no-selection \
  --no-click \
  --tail \
  --close-on-unfocus \
  --progress \
  --bar=" T " "$battery_percent%" \
  --bar=" 0 " "$battery_percent_0%" \
  --bar=" 1 " "$battery_percent_1%" 

  # --image="$image" \
