#!/usr/bin/env bash

# xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/'

screen_width=1920
width=360

# to the right most position
posx=-1
posy=32

# to the center
# posx=$(("($screen_width - $width) / 2"))
# posx=780

yad --calendar \
    --show-weeks \
    --no-buttons \
    --close-on-unfocus \
    --width=$width \
    --posx=$posx \
    --posy=$posy 

    # --posy=$posy \
    # --image=preferences-system-time-symbolic
