#!/usr/bin/env bash

PATH_AC="/sys/class/power_supply/AC"
PATH_BATTERY_0="/sys/class/power_supply/BAT0"
PATH_BATTERY_1="/sys/class/power_supply/BAT1"

ac=0
battery_level_0=0
battery_level_1=0
battery_max_0=0
battery_max_1=0

battery_L_color="$(xrdb -query | grep color1: | cut -f 2)"
battery_F_color="$(xrdb -query | grep color2: | cut -f 2)"

[ -f "$PATH_AC/online" ]             && ac=$(cat "$PATH_AC/online")
[ -f "$PATH_BATTERY_0/energy_now" ]  && battery_level_0=$(cat "$PATH_BATTERY_0/energy_now")
[ -f "$PATH_BATTERY_1/energy_now" ]  && battery_level_1=$(cat "$PATH_BATTERY_1/energy_now")
[ -f "$PATH_BATTERY_0/energy_full" ] && battery_max_0=$(cat "$PATH_BATTERY_0/energy_full")
[ -f "$PATH_BATTERY_1/energy_full" ] && battery_max_1=$(cat "$PATH_BATTERY_1/energy_full")

battery_level=$(("$battery_level_0 + $battery_level_1"))
battery_max=$(("$battery_max_0 + $battery_max_1"))

battery_percent=$(("$battery_level * 100"))
battery_percent=$(("$battery_percent / $battery_max"))

icons=(󰂎 󰁺 󰁻 󰁼 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹 󰂄)

icon="${icons[ (($battery_percent / 10)) ]}"
[ "$battery_percent" -gt 96 ] && icon="${icons[10]}"
[ "$ac" -eq 1 ] && icon="${icons[11]}"

msg="$icon"

if [ "$battery_percent" -ge 99 ]; then
  msg="%{F$battery_F_color}$msg%{F-}"
elif [ "$battery_percent" -le 8 ]; then
  msg="%{F$battery_L_color}$msg%{F-}"
fi

echo "$msg"
