#!/usr/bin/env bash

[[ "${FLOCKER}" != "$0" ]] && exec env FLOCKER="$0" flock -Fxn "$0" "$0" "$@" || :

set -m

readonly dirs=(
    /usr/share/applications
    /usr/local/share/applications
    $HOME/.local/share/applications
)

# in the dirs, build a dictionary:
# xyz.desktop -> /path/to/xyz.desktop

declare -A files
for d in "${dirs[@]}"; do
    for f in $(ls -1 ${d}/*.desktop 2> /dev/null); do
        name=${f##*/}
        files[${name}]=$f
    done
done

for f in "${files[@]}"; do
    awk -F= '

        /^NoDisplay=true/ {no_display=1}
        /^Name=/ {if (!name) {name=$2}}

        END {if (!no_display) {print FILENAME,name}}

     ' $f
done 2> /dev/null | sort -k 2 |
    fzf --reverse                            \
        --no-info                            \
        --border                             \
        --scrollbar ┆ --color scrollbar:blue \
        --with-nth=2..                       \
        --prompt "Run: " | {
    pick=$(cut -d' ' -f1)
    [[ -n ${pick} ]] && gio launch ${pick} &> /dev/null &
}
