#!/usr/bin/env bash

xrdb ~/.Xresources &
feh --bg-scale ~/Pictures/Wallpapers/wallpaper &
compton -b &
urxvtd -q -f -o &

xsetroot -cursor_name left_ptr &

xset s 300 5 &
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

# autostart some programs
~/.config/scripts/bspwm_launch_polybar &
