#!/usr/bin/env python
import subprocess

msgId="1547391577"
battery = "BAT0"
battery_uevent = "/sys/class/power_supply/" + battery + "/uevent"

with open(battery_uevent, 'r') as f:
    for line in f:
        if "ENERGY_NOW" in line:
            energy_now = int(line.split('=')[1])
        if "POWER_NOW" in line:
            power_now = int(line.split('=')[1])

if power_now > 0:
    remaining_time = energy_now / power_now
    h = int(remaining_time)
    m = int((remaining_time - h) * 60)
    msg = "%d:%02d remaining" %(h, m)

    subprocess.run(["dunstify", "-a", "Display Battery", "-u", "normal", "-r", msgId, battery, msg])
