# User specific environment and startup programs
export CDPATH=".:$HOME"

# homebrew
export PATH=/opt/homebrew/bin:$PATH

# editor
export EDITOR='vim'

# manpager
export MANPAGER='vim +MANPAGER "+set laststatus=0" "+noremap q <Cmd>qall!<CR>" --not-a-term -'

# less
export LESSHISTFILE=-

# python
export PYTHONSTARTUP=$HOME/.config/python/pythonrc
export VIRTUAL_ENV_DISABLE_PROMPT=1
