# set history options
HISTSIZE=20000
HISTFILESIZE=20000

setopt AUTO_CD
setopt AUTO_PUSHD
setopt BANG_HIST
setopt COMPLETE_IN_WORD
setopt CORRECT
setopt CORRECT_ALL
setopt EXTENDED_HISTORY
setopt HIST_BEEP
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
setopt PROMPT_SUBST
setopt SHARE_HISTORY

# define user specific aliases and functions
alias ls="ls -F -D '%F %R' --color=always"
alias ll="ls -l"
alias la="ll -a"

alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"

alias bc="bc --mathlib"

alias diff="diff --color=always"

alias  grep="grep --color=always"
alias egrep="egrep --color=always"
alias fgrep="fgrep --color=always"

alias less="LESSHISTFILE=- less -FXR --mouse --wheel-lines=3"
alias rsync="rsync --progress"

[[ "$TERM" = "xterm-kitty" ]] && alias ssh="kitty +kitten ssh"

# enable autoloads
autoload -Uz add-zsh-hook

# autojump
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-default yes
zstyle ':completion:*' recent-dirs-insert always
alias j=cdr

# enable auto-completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

# key binds
bindkey -M viins '^R' history-incremental-search-backward
bindkey -M vicmd '^R' history-incremental-search-backward

# customize shell prompt
autoload -Uz vcs_info
add-zsh-hook precmd vcs_info

zstyle ':vcs_info:*'     enable            git
zstyle ':vcs_info:*'     check-for-changes true
zstyle ':vcs_info:*'     stagedstr         '%F{yellow}'
zstyle ':vcs_info:*'     unstagedstr       '%F{red}'
zstyle ':vcs_info:git:*' formats           '%F{green}%u%c* %b%f'
zstyle ':vcs_info:git:*' actionformats     '%u%c%b (%F{blue}%a%f)'

# add a newline before each prompt
precmd() {
    precmd() {
        echo
    }
}

# set the prompt using anonymous function
() {
    PROMPT=''
    PROMPT+='┌ %F{blue}%n%f@%m:%F{blue}%~%f ${vcs_info_msg_0_}'
    PROMPT+=$'\n'
    PROMPT+='└ %(?.%F{green}.%F{red})%#%f '

    RPROMPT='%F{magenta}%T%f'
}

