#!/usr/bin/env bash

# ensure to add user to the video group
# sudo usermod -a -G video `whoami`

# add the following udev rules
# /etc/udev/rules/90-backlight.rules

# SUBSYSTEM=="backlight", ACTION=="add",
# RUN+="/bin/chgrp video /sys/class/backlight/intel_backlight/brightness",
# RUN+="/bin/chmod g+w   /sys/class/backlight/intel_backlight/brightness"

# $1 : delta in brightness (0-100)

msgid=246135
BACKLIGHT_BRIGHTNESS=/sys/class/backlight/intel_backlight/brightness

delta=$(( $1 * 12 )) # adjust to (0-1200)
brightness=$(( $(cat $BACKLIGHT_BRIGHTNESS) + ${delta} ))

echo $brightness > $BACKLIGHT_BRIGHTNESS

brightness=$(( $brightness / 12 ))
dunstify --appname "hlwm-update-brightness" \
         --timeout 1500                     \
         --urgency low                      \
         --icon dialog-information          \
         --replace "${msgid}"               \
         --hints int:value:"${brightness}" "Brightness: ${brightness}%"
