#!/usr/bin/env bash

[[ "${FLOCKER}" != "$0" ]] && exec env FLOCKER="$0" flock -Fxn "$0" "$0" "$@" || :

map=(
    "Lock"      "xsecurelock"
    "Log Out"   "pkill -SIGTERM -t tty${XDG_VTNR} Xorg"
    "Reboot"    "systemctl reboot"
    "Power Off" "systemctl poweroff"
    "Suspend"   "systemctl suspend"
)

delimiter=":"
for (( i=0; i<${#map[@]}; i+=2 )); do
    echo "${map[i+1]}${delimiter}${map[i]}"
done | fzf --prompt "Go: "          \
           --reverse                \
           --border                 \
           --no-info                \
           --delimiter=${delimiter} \
           --with-nth=2.. | {
    cmd=$(cut -d${delimiter} -f1)
    exec $cmd
}
