#!/usr/bin/env bash

[[ "${FLOCKER}" != "$0" ]] && exec env FLOCKER="$0" flock -Fxn "$0" "$0" "$@" || :

map=(
    "Lock"      "xsecurelock"
    "Log Out"   "pkill -SIGTERM -t tty${XDG_VTNR} Xorg"
    "Reboot"    "systemctl reboot"
    "Power Off" "systemctl poweroff"
    "Suspend"   "systemctl suspend"
)

for (( i=0; i<${#map[@]}; i+=2 )); do
    echo "${map[i]}"
done | rofi -i -format 'i' -dmenu -p 'I would like to' | {
    read idx
    idx=$(( $idx * 2 + 1 ))
    cmd="${map[$idx]}"
    exec $cmd
}
