#!/usr/bin/env bash

actions=(
    'Lock'
    'Log Out'
    'Reboot'
    'Power Off'
    'Suspend'
)

commands=(
    'env xsecurelock'
    'herbstclient quit'
    'systemctl reboot'
    'systemctl poweroff'
    'systemctl suspend'
)

menu=''
for a in "${actions[@]}"; do
    menu+="$a"
    menu+='\n'
done

index=$(echo -e ${menu}                                                        \
             | awk '{print NR-1, $0}'                                          \
             | fzf --prompt "Go: " --reverse --border --no-info --with-nth=2.. \
             | cut -d' ' -f1)

if [ $index -ge 0 ]; then
    eval ${commands[$index]}
else
    exit 1
fi
