#!/usr/bin/bash

hc() {
    herbstclient "$@"
}

# launch a few programs
xset s 300 5 
picom --daemon --fading --no-fading-openclose
light-locker &

if [ -f $HOME/.fehbg ]; then
  hc spawn $HOME/.fehbg
fi

# launch polybar
polybar=~/.config/herbstluftwm/herbstluftwm_launch_polybar
if [ -x "$polybar" ]; then
  # padding to accomodate polybar
  hc pad 0 36 0 0 0

  # launch 
  $polybar
fi
