#!/usr/bin/env bash

xrdb ~/.Xresources

# launch a few programs
xsetroot -cursor_name left_ptr

# lock after 5 min / suspend after 2 min
xset s 300 5
xss-lock --notifier=/usr/libexec/xsecurelock/dimmer \
         --transfer-sleep-lock                      \
         -- env XSECURELOCK_COMPOSITE_OBSCURER=0 xsecurelock &

# workaround a java bug for jetbrain products
herbstclient cycle_value wmname herbstluftwm LG3D

# compositor
picom --daemon

# set wallpaper
feh --no-fehbg --image-bg "#000000" --bg-center /usr/share/pixmaps/fedora-logo.png

# source .xprofile
source ~/.xprofile

# start ibus daemon
ibus-daemon -drx &

# terminate already running bar instances
pkill -u $UID -f termbar

# wait until the processes have been shut down
while pgrep -u $UID -f termbar >/dev/null; do sleep 1; done

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
herbstclient detect_monitors

# launch termbar
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    herbstclient pad $monitor 34
    exec -a termbar xterm -class termbar -e ~/.config/herbstluftwm/termbar $monitor &
done

canberra-gtk-play --id desktop-login
