#!/usr/bin/env bash

# lock after 5 min / suspend after 2 min
xset s 300 5
xss-lock --notifier=/usr/libexec/xsecurelock/dimmer \
         --transfer-sleep-lock                      \
         -- env XSECURELOCK_COMPOSITE_OBSCURER=0 xsecurelock &

# workaround a java bug for jetbrain products
herbstclient cycle_value wmname herbstluftwm LG3D

# compositor
picom --daemon

# set wallpaper
feh --no-fehbg --image-bg "#000000" --bg-center /usr/share/pixmaps/fedora-logo.png

# start ibus daemon
ibus-daemon -drx &

# terminate already running bar instances
pkill -u $UID -f termbar

# wait until the processes have been shut down
while pgrep -u $UID -f termbar >/dev/null; do sleep 1; done

# do multi monitor setup here, e.g.:
# herbstclient set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
herbstclient detect_monitors

# launch termbar on primary monitor
herbstclient pad 0 35
exec -a termbar kitty                      \
     --class termbar                       \
     --config ~/.config/kitty/termbar.conf \
     --single-instance                     \
     --instance-group=termbar              \
     ~/.config/herbstluftwm/termbar 0 &

if [[ $(herbstclient get_attr monitors.count) > 1 ]]; then
    # put the external monitor on the right
    xrandr --output eDP-1 --primary --auto --output HDMI-2 --auto --right-of eDP-1

    herbstclient focus_monitor 1
    herbstclient use 0
    herbstclient lock_tag 1

    herbstclient focus_monitor 0
fi

# install battery monitor
battery-monitor &

canberra-gtk-play --id desktop-login
