#!/usr/bin/env bash

msgid=321567
focused_monitor=$(herbstclient get_attr monitors.focus.index)

dunstify --appname "hlwm-switch-monitor" \
         --timeout 1000                  \
         --urgency low                   \
         --icon computer                 \
         --replace "$msgid"              \
         "Monitor: ${focused_monitor}"
