#!/usr/bin/env python

import os
from datetime import datetime
from zoneinfo import ZoneInfo
import gi

os.environ["GTK_THEME"] = "Adwaita:dark"

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, Gdk

screen_width = 1920
width = 360
height = 360
posy = 30
posx = (screen_width - width) / 2

clocks = [
    "America/Toronto",
    "America/Vancouver",
    "Asia/Shanghai"
]

class ShowTimeWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="Show Time")

        self.set_type_hint(Gdk.WindowTypeHint.NORMAL)
        self.set_default_size(width, height)
        self.move(posx, posy)
        self.connect("focus-out-event", Gtk.main_quit)

        vbox = Gtk.Box.new(Gtk.Orientation.VERTICAL, 3)
        self.add(vbox)

        # banner
        today = datetime.today()

        label = Gtk.Label.new()
        label.set_text(today.strftime("%A"))
        label.set_xalign(0.03)
        vbox.add(label)

        label = Gtk.Label.new()
        label.set_markup(today.strftime("<big><b>%B %e %Y</b></big>"))
        label.set_xalign(0.03)
        vbox.add(label)

        # separator
        vbox.add(Gtk.Separator.new(Gtk.Orientation.HORIZONTAL))

        # calendar
        calendar = Gtk.Calendar.new()
        calendar.set_display_options(Gtk.CalendarDisplayOptions.SHOW_HEADING
                                     | Gtk.CalendarDisplayOptions.SHOW_DAY_NAMES
                                     |Gtk.CalendarDisplayOptions.SHOW_WEEK_NUMBERS)
        vbox.add(calendar)

        # separator
        vbox.add(Gtk.Separator.new(Gtk.Orientation.HORIZONTAL))

        label = Gtk.Label.new(None)
        label.set_markup("<b>World Clocks</b>")
        label.set_xalign(0.03)

        vbox.add(label)

        # separator
        vbox.add(Gtk.Separator.new(Gtk.Orientation.HORIZONTAL))

        grid = Gtk.Grid.new()
        vbox.add(grid)
        for i, c in enumerate(clocks):
            dt = datetime.now(ZoneInfo(c))

            # timezone
            text = " {0:23s}".format(c.split("/")[1])
            label = Gtk.Label.new(None)
            label.set_text(text)
            label.set_xalign(0.0)
            grid.attach(label, 0, i, 1, 1)

            # time
            text = "{0:9d}:{1:02d}".format(dt.hour, dt.minute)
            label = Gtk.Label.new(None)
            label.set_text(text)
            label.set_xalign(1.0)
            grid.attach(label, 1, i, 1, 1)

            # utc offset
            text = "{0:+19.1f}".format(dt.tzinfo.utcoffset(dt).total_seconds() / 3600)
            label = Gtk.Label.new(None)
            label.set_text(text)
            label.set_xalign(1.0)
            grid.attach(label, 2, i, 1, 1)

if __name__ == "__main__":
    Gdk.set_program_class("hlwm-show-time")

    win = ShowTimeWindow()
    win.show_all()

    Gtk.main()
