#!/usr/bin/env python

import os
import subprocess
import enum
import gi

os.environ["GTK_THEME"] = "Adwaita:dark"

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, Gdk

gap = 2
screen_width = 1920
width = 300
height = 50
posy = 30 + gap
posx = screen_width - width - gap

BACKLIGHT_BRIGHTNESS = "/sys/class/backlight/intel_backlight/brightness"

class Actions(enum.IntEnum):
    Lock = 1
    LogOut = 2
    Reboot = 3
    PowerOff = 4
    Suspend = 5

actions = {
    Actions.Lock     : ["", "Lock",      "light-locker-command --lock"],
    Actions.LogOut   : ["", "Log Out",   "herbstclient quit"],
    Actions.Reboot   : ["", "Reboot",    "systemctl reboot"],
    Actions.PowerOff : ["", "Power Off", "systemctl poweroff"],
    Actions.Suspend  : ["", "Suspend",   "systemctl suspend"]
}

def get_brightness():
    f = open(BACKLIGHT_BRIGHTNESS,"r")
    brightness = int(f.read()) / 12
    f.close()

    return brightness

def set_brightness(brightness):
    f = open(BACKLIGHT_BRIGHTNESS,"w")
    f.write(str(int(brightness * 12)))
    f.close()

def get_volume():
    return int(subprocess.Popen(["pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}'| grep -m 1 % | sed 's/[%|,]//g'"], shell=True,
                              stdout=subprocess.PIPE,
                              universal_newlines=True).stdout.read())

def set_volume(vol):
    muted = subprocess.Popen(["pactl get-sink-mute @DEFAULT_SINK@ | cut -d ' ' -f 2"], shell=True,
                              stdout=subprocess.PIPE,
                              universal_newlines=True).stdout.read().strip()
    muted = "1" if muted == "yes" else "0"

    vol = str(int(vol)).strip()
    subprocess.Popen(["pactl", "set-sink-volume", "@DEFAULT_SINK@", vol + "%"])
    subprocess.Popen(["herbstclient", "emit_hook", "vol", muted, vol])

def get_essid():
    return subprocess.Popen(["iwctl station wlan0 show | grep 'Connected network' | awk '{print $3}'"], shell=True,
                              stdout=subprocess.PIPE,
                              universal_newlines=True).stdout.read().strip()

class ActionDialog(Gtk.Dialog):
    def __init__(self, parent, a):
        super().__init__(title="Are you sure?", transient_for=parent, flags=0)

        self.set_border_width(20)
        self.set_default_size(150, 150)
        self.set_position(Gtk.WindowPosition.CENTER_ALWAYS)

        button = self.add_button(Gtk.STOCK_YES, Gtk.ResponseType.YES)
        button.set_always_show_image(True)

        button = self.add_button(Gtk.STOCK_NO, Gtk.ResponseType.NO)
        button.set_always_show_image(True)

        hbox = Gtk.Box.new(Gtk.Orientation.HORIZONTAL, 30)

        label = Gtk.Label.new()
        text = "Are you sure you want to " + actions[a][1].lower() + " your computer now?"
        label.set_text(text)

        image = Gtk.Image()
        image.set_from_icon_name("dialog-question", Gtk.IconSize.DIALOG)
        image.show()

        hbox.add(image)
        hbox.add(label)

        ca = self.get_content_area()
        ca.add(hbox)
        self.show_all()

class ShowTrayWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="Show Time")

        self.set_type_hint(Gdk.WindowTypeHint.NORMAL)
        self.set_default_size(width, height)
        self.set_border_width(7)
        self.move(posx, posy)
        self.connect("focus-out-event", Gtk.main_quit)

        vbox = Gtk.Box.new(Gtk.Orientation.VERTICAL, 3)
        self.add(vbox)

        # brightness
        hbox = Gtk.Box.new(Gtk.Orientation.HORIZONTAL, 3)
        vbox.add(hbox)

        label = Gtk.Label.new()
        label.set_text("{0:2s}".format(""))
        label.set_xalign(0.03)
        hbox.add(label)

        self.brightnessScale = Gtk.Scale.new_with_range(Gtk.Orientation.HORIZONTAL, 0, 100, 5)
        self.brightnessScale.set_value(get_brightness())
        self.brightnessScale.set_draw_value(False)
        self.brightnessScale.set_size_request(260, 0)
        self.brightnessScale.connect("value-changed", self.on_change_brightness)
        hbox.add(self.brightnessScale)

        # volume
        hbox = Gtk.Box.new(Gtk.Orientation.HORIZONTAL, 3)
        vbox.add(hbox)

        label = Gtk.Label.new()
        label.set_text("{0:2s}".format(""))
        label.set_xalign(0.03)
        hbox.add(label)

        self.volumeScale = Gtk.Scale.new_with_range(Gtk.Orientation.HORIZONTAL, 0, 150, 5)
        self.volumeScale.set_value(get_volume())
        self.volumeScale.set_draw_value(False)
        self.volumeScale.set_size_request(260, 0)
        self.volumeScale.add_mark(100, Gtk.PositionType.TOP, None)
        self.volumeScale.connect("value-changed", self.on_change_volume)
        hbox.add(self.volumeScale)

        # separator
        vbox.add(Gtk.Separator.new(Gtk.Orientation.HORIZONTAL))

        # network
        hbox = Gtk.Box.new(Gtk.Orientation.HORIZONTAL, 3)
        vbox.add(hbox)

        label = Gtk.Label.new()
        label.set_text("{0:2s}".format(""))
        label.set_xalign(0.03)
        hbox.add(label)

        self.essidLabel = Gtk.Label.new()
        self.essidLabel.set_text(get_essid())
        self.essidLabel.set_xalign(0.03)
        self.essidLabel.set_size_request(260, 0)
        hbox.add(self.essidLabel)

        # power supply
        hbox = Gtk.Box.new(Gtk.Orientation.HORIZONTAL, 3)
        vbox.add(hbox)

        label = Gtk.Label.new()
        label.set_text("{0:2s}".format(""))
        label.set_xalign(0.03)
        hbox.add(label)

        self.batxExpander = Gtk.Expander.new()
        self.batxExpander.set_label("55%")
        self.batxExpander.set_label_fill(True)
        hbox.add(self.batxExpander)

        # bat0 = Gtk.Label.new()
        # label.set_text("BAT0")
        # # self.batxExpander.add(bat0)

        # bat1 = Gtk.Label.new()
        # label.set_text("BAT1")
        # self.batxExpander.add(bat1)

        # separator
        vbox.add(Gtk.Separator.new(Gtk.Orientation.HORIZONTAL))

        # actions
        for a in actions:
            hbox = Gtk.Box.new(Gtk.Orientation.HORIZONTAL, 3)
            vbox.add(hbox)

            label = Gtk.Label.new()
            label.set_text("{0:2s}".format(actions[a][0]))
            label.set_xalign(0.03)
            hbox.add(label)

            button = Gtk.Button.new()
            button.set_label(actions[a][1])
            button.set_relief(Gtk.ReliefStyle.NONE)
            button.connect("clicked", self.on_click_action, a)
            hbox.add(button)

    def on_change_brightness(self, scale):
        set_brightness(scale.get_value())

    def on_change_volume(self, scale):
        set_volume(scale.get_value())

    def on_click_action(self, button, a):
        dialog = ActionDialog(self, a)
        response = dialog.run()
        dialog.destroy()

        if response == Gtk.ResponseType.YES:
            subprocess.Popen(actions[a][2], shell=True, stdout=subprocess.PIPE)


if __name__ == "__main__":
    Gdk.set_program_class("hlwm-show-tray")

    win = ShowTrayWindow()
    win.show_all()

    Gtk.main()
