#!/usr/bin/env bash

HLWM_HOME=$HOME/.config/herbstluftwm

if [[ $1 =~ ^tbp:\/\/wm\/ws\/[1-9]$ ]]; then # tbp://wm/ws/${tag_name}
    tag=${1##*/}
    herbstclient use "${tag}"
elif [[ $1 =~ ^tbp:\/\/wm\/bye$ ]]; then # tbp://wm/bye

    kitty --class fzmenu $HLWM_HOME/sayonara
fi
