#!/usr/bin/env bash

# $1: press mute button
# $2: delta in volume

delta=$2
[[ "$1" -eq 1 ]] && pactl set-sink-mute @DEFAULT_SINK@ toggle
muted=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -d ' ' -f 2)

[[ "${muted}" == "yes" ]] && muted=1
[[ "${muted}" == "no" ]] && muted=0

[[ "${delta}" -ne 0 ]] && pactl set-sink-volume @DEFAULT_SINK@ "${delta}%"

vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}'| grep -m 1 % | sed 's/[%|,]//g')

herbstclient emit_hook vol "${muted}" "${vol}"
