#!/usr/bin/env bash

# $1: press mute button
# $2: delta in volume

msgid=123456
delta=$2

# get default node name
default_node_name=$(wpctl status|grep -A2 Default|tail -1|awk '{print $3}')

# get its node_id
node_id=$(pw-dump|jq --arg default_node_name $default_node_name '.[]|select(.info.props["node.name"] == $default_node_name)|.id')

[[ "$1" -eq 1 ]] && wpctl set-mute "$node_id" toggle 

# true - false
muted=$(wpctl status|grep ${node_id}[.]|awk -F '[][]' '{print $2}'|awk '{print $3}')
echo $muted
if [[ $muted == "MUTED" ]]; then
    muted=true
else
    muted=false
fi

# vol -> (0.00, 1.00)
vol=$(wpctl status|grep ${node_id}[.]|awk -F '[][]' '{print $2}'|awk '{print $2}')

delta=$(printf "%d" $delta)
if [[ "${delta}" -ne 0 ]]; then
    vol=$(echo "$delta / 100 + $vol"|bc -l)
    wpctl set-volume $node_id $vol
fi
vol=$(printf "%.0f" $(echo "${vol} * 100"|bc -l))

herbstclient emit_hook vol "${muted}" "${vol}"

if [ $muted == true ]; then
    dunstify --appname "hlwm-update-volume" \
             --timeout 1500                 \
             --urgency low                  \
             --icon audio-volume-muted      \
             --replace "$msgid" "Volume muted"
else
    if [ "${vol}" -gt 66 ]; then
        icon="audio-volume-high"
    elif [ "${vol}" -gt 33 ]; then
        icon="audio-volume-medium"
    elif [ "${vol}" -gt 0 ]; then
        icon="audio-volume-low"
    else
        icon="audio-volume-muted"
    fi

    dunstify --appname "hlwm-update-volume" \
             --timeout 1500                 \
             --urgency low                  \
             --icon "$icon"                 \
             --replace "$msgid"             \
             --hints int:value:"$vol" "Volume: ${vol}%"

    canberra-gtk-play --id audio-volume-change --description "hlwm-update-volume"
fi
