#!/usr/bin/env bash

# $1: press mute button
# $2: delta in volume

delta=$2

[[ "$1" -eq 1 ]] && wpctl set-mute @DEFAULT_SINK@ toggle

[[ "${delta}" != "0" ]] && wpctl set-volume @DEFAULT_SINK@ ${delta}

vol_info=$(wpctl get-volume @DEFAULT_SINK@)
vol=$(bc <<< "$(cut -d' ' -f2 <<< ${vol_info}) * 100" | cut -d. -f1)
muted=$(cut -d' ' -f3 <<< $vol_info)
if [[ $muted == "[MUTED]" ]]; then
    muted=1
else
    muted=0
fi

herbstclient emit_hook vol "${muted}" "${vol}"

if [ $muted == 1 ]; then
    dunstify --appname "wm-update-volume"                      \
             --timeout 1500                                    \
             --urgency low                                     \
             --icon audio-volume-muted                         \
             --hints string:x-dunst-stack-tag:wm-update-volume \
             "Volume: MUTED"
else
    if [ "${vol}" -gt 66 ]; then
        icon="audio-volume-high"
    elif [ "${vol}" -gt 33 ]; then
        icon="audio-volume-medium"
    elif [ "${vol}" -gt 0 ]; then
        icon="audio-volume-low"
    else
        icon="audio-volume-muted"
    fi

    dunstify --appname "wm-update-volume"                      \
             --timeout 1500                                    \
             --urgency low                                     \
             --icon "$icon"                                    \
             --hints string:x-dunst-stack-tag:wm-update-volume \
             --hints int:value:"$vol"                          \
             "Volume: ${vol}%"

    canberra-gtk-play --id audio-volume-change --description "wm-update-volume"
fi
