#!/usr/bin/env bash

# $1: press mute button
# $2: delta in volume

msgid=123456
delta=$2

[[ "$1" -eq 1 ]] && wpctl set-mute @DEFAULT_SINK@ toggle

[[ "${delta}" != "0" ]] && wpctl set-volume @DEFAULT_SINK@ ${delta}

vol_info=$(wpctl get-volume @DEFAULT_SINK@)
vol=$(bc <<< "$(cut -d' ' -f2 <<< ${vol_info}) * 100" | cut -d. -f1)
muted=$(echo $vol_info | cut -d' ' -f3)
if [[ $muted == "[MUTED]" ]]; then
    muted=true
else
    muted=false
fi

herbstclient emit_hook vol "${muted}" "${vol}"

if [ $muted == true ]; then
    dunstify --appname "hlwm-update-volume" \
             --timeout 1500                 \
             --urgency low                  \
             --icon audio-volume-muted      \
             --replace "$msgid" "Volume: MUTED"
else
    if [ "${vol}" -gt 66 ]; then
        icon="audio-volume-high"
    elif [ "${vol}" -gt 33 ]; then
        icon="audio-volume-medium"
    elif [ "${vol}" -gt 0 ]; then
        icon="audio-volume-low"
    else
        icon="audio-volume-muted"
    fi

    dunstify --appname "hlwm-update-volume" \
             --timeout 1500                 \
             --urgency low                  \
             --icon "$icon"                 \
             --replace "$msgid"             \
             --hints int:value:"$vol" "Volume: ${vol}%"

    canberra-gtk-play --id audio-volume-change --description "hlwm-update-volume"
fi
