#!/usr/bin/env bash

# ensure to add user to the video group
# sudo usermod -a -G video `whoami`

# add the following udev rules
# /etc/udev/rules/90-backlight.rules

# SUBSYSTEM=="backlight", ACTION=="add",
# RUN+="/bin/chgrp video /sys/class/backlight/intel_backlight/brightness",
# RUN+="/bin/chmod g+w   /sys/class/backlight/intel_backlight/brightness"

# $1 : delta in brightness (0-100)

BACKLIGHT_BRIGHTNESS_PATH=/sys/class/backlight/intel_backlight

actual=$(cat "${BACKLIGHT_BRIGHTNESS_PATH}/actual_brightness")
max=$(cat "${BACKLIGHT_BRIGHTNESS_PATH}/max_brightness")
one_perc=$(( "${max}" / 100 ))
delta=$(( "${one_perc}" * "$1" ))
now=$(( "${actual}" + "${delta}" ))

[[ $now -lt 0 ]] && now=0

echo $now >  "${BACKLIGHT_BRIGHTNESS_PATH}/brightness"

brightness=$(( $now * 100 / $max ))

dunstify --appname "wm-update-brightness"                      \
         --timeout 1500                                        \
         --urgency low                                         \
         --icon dialog-information                             \
         --hints string:x-dunst-stack-tag:wm-update-brightness \
         --hints int:value:"${brightness}"                     \
         "Brightness: ${brightness}%"
