#!/usr/bin/env bash

focused_monitor=$(herbstclient get_attr monitors.focus.index)

dunstify --appname "wm-switch-monitor"                      \
         --timeout 1000                                     \
         --urgency low                                      \
         --icon computer                                    \
         --hints string:x-dunst-stack-tag:wm-switch-monitor \
         "Monitor: ${focused_monitor}"
