# Get the aliases and functions
[[ -f ~/.bashrc ]] && source ~/.bashrc

# User specific environment and startup programs
export CDPATH=".:$HOME"
export XDG_CONFIG_HOME=$HOME/.config

# homebrew
if type brew &>/dev/null; then
    source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
fi

# editor
export EDITOR='vim'

# fzf
if type fzf &>/dev/null; then
    eval "$(fzf --bash)"

    export FZF_DEFAULT_OPTS='
    --height ~9 --reverse --style minimal --no-info
    --preview "cat {}"
    --preview-window right:60%:hidden:wrap
    --bind ctrl-y:toggle-preview
    '
fi

# manpager
export MANPAGER='vim +MANPAGER --not-a-term -'

# less
export LESSHISTFILE=-

# python
export PYTHON_HISTORY=$HOME/.local/share/python/history
export VIRTUAL_ENV_DISABLE_PROMPT=1

# go
export GOPATH=$HOME/.local/share/go

# readline
export INPUTRC=$HOME/.config/readline/inputrc

# pass
export PASSWORD_STORE_DIR=$HOME/.local/share/pass
export PASSWORD_STORE_GENERATED_LENGTH=20
