#
# ~/.bash_profile
#

# Get the aliases and functions
[[ -f ~/.bashrc ]] && source ~/.bashrc

# User specific environment and startup programs
export CDPATH=".:$HOME"

# less
export LESSHISTFILE=-

# python
export PYTHONSTARTUP=$HOME/.config/python/pythonrc
export VIRTUAL_ENV_DISABLE_PROMPT=1

# readline
export INPUTRC=$HOME/.config/readline/inputrc

